name: 下载JM本子 (dispatch)

on:
  workflow_dispatch:
    inputs:
      JM_ALBUM_IDS:
        type: string
        description: 本子id（多个id用-隔开，如 '123-456-789'）
        required: false

      JM_PHOTO_IDS:
        type: string
        description: 章节id（单独下载章节，多个id同上）
        required: false

      CLIENT_IMPL:
        type: string
        description: 客户端类型（client.impl），下载失败时，你可以尝试填入此项重试。'api' 表示移动端，'html' 表示网页端。
        default: ''
        required: false

      IMAGE_SUFFIX:
        type: string
        description: 图片后缀（download.cache.suffix），默认为空，表示不做图片格式转换。可填入例如 'png' 'jpg'
        default: ''
        required: false

      DIR_RULE:
        type: string
        description: 下载文件夹规则（dir_rule.rule）。默认使用配置文件的 'Bd_Aauthor_Atitle_Pindex'。
        default: ''
        required: false

      ZIP_NAME:
        type: string
        default: 本子.tar.gz
        description: 压缩文件名称
        required: false

      UPLOAD_NAME:
        type: string
        default: Click me to download
        description: 上传文件名称
        required: false

jobs:
  crawler:
    runs-on: ubuntu-latest
    env:
      # 工作流输入
      JM_ALBUM_IDS: ${{ github.event.inputs.JM_ALBUM_IDS }}
      JM_PHOTO_IDS: ${{ github.event.inputs.JM_PHOTO_IDS }}
      DIR_RULE: ${{ github.event.inputs.DIR_RULE }}
      CLIENT_IMPL: ${{ github.event.inputs.CLIENT_IMPL }}
      ZIP_NAME: ${{ github.event.inputs.ZIP_NAME }}
      UPLOAD_NAME: ${{ github.event.inputs.UPLOAD_NAME }}
      IMAGE_SUFFIX: ${{ github.event.inputs.IMAGE_SUFFIX }}

      # 登录相关secrets
      JM_USERNAME: ${{ secrets.JM_USERNAME }}
      JM_PASSWORD: ${{ secrets.JM_PASSWORD }}

      # 邮件相关secrets
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TITLE: ${{ secrets.EMAIL_TITLE }}
      EMAIL_CONTENT: ${{ secrets.EMAIL_CONTENT }}

      # 固定值
      JM_DOWNLOAD_DIR: /home/runner/work/jmcomic/download/
      BOT_TOKEN: ${{ secrets.BOT }}  # Telegram Bot Token
      TELEGRAM_CHAT_ID: -1002450004109  # 目标频道的 Chat ID

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: 安装jmcomic（pip）
        if: ${{ github.ref != 'refs/heads/dev' }}
        run: |
          pip install jmcomic -i https://pypi.org/project --upgrade

      - name: 安装jmcomic（local）
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          pip install -e ./

      - name: 运行下载脚本
        run: |
          cd ./usage/
          python workflow_download.py

      - name: 压缩文件
        run: |
          mkdir -p $JM_DOWNLOAD_DIR
          cd $JM_DOWNLOAD_DIR
          tar -zcvf "../$ZIP_NAME" ./
          mv "../$ZIP_NAME" .

      - name: 上传结果
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.UPLOAD_NAME }}
          path: ${{ env.JM_DOWNLOAD_DIR }}/${{ env.ZIP_NAME }}
          if-no-files-found: error
          retention-days: 90

      - name: 触发 Webhook
        run: |
          # 生成 GET 请求的 URL（参数直接拼接到 URL 中）
          DOWNLOAD_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload-artifact.outputs.artifact-id }}"
          curl -G "http://124.71.134.95:5678/webhook-test/07e50f86-11ed-4781-9990-afc7beb562b7" \
            --data-urlencode "url=$DOWNLOAD_URL"

      - name: 发送多个图片到 Telegram 频道
        run: |
          cd "$JM_DOWNLOAD_DIR"
      
          # 获取 JPG 文件列表并排序
          JPG_FILES=$(ls *.jpg 2>/dev/null | sort -V)
          if [ -z "$JPG_FILES" ]; then
            echo "未找到 JPG 文件，跳过发送。"
            exit 0
          fi
      
          # 将文件列表转为数组
          FILES_ARRAY=($JPG_FILES)
          
          # 构建媒体组 JSON
          MEDIA_GROUP="["
          for FILE in "${FILES_ARRAY[@]}"; do
            MEDIA_GROUP+="{\"type\":\"photo\",\"media\":\"attach://$FILE\"},"
          done
          MEDIA_GROUP=${MEDIA_GROUP%,}  # 移除最后一个逗号
          MEDIA_GROUP+="]"
      
          # 构建 curl 命令
          CURL_CMD="curl -X POST \"https://api.telegram.org/bot$BOT_TOKEN/sendMediaGroup\" \
            -F \"chat_id=$TELEGRAM_CHAT_ID\" \
            -F \"media=$MEDIA_GROUP\""
      
          # 添加文件附件
          for FILE in "${FILES_ARRAY[@]}"; do
            CURL_CMD+=" -F \"$FILE=@$FILE\""
          done
      
          # 执行请求
          echo "正在发送文件: ${FILES_ARRAY[*]}"
          eval "$CURL_CMD"
      
          echo "图片发送完成。"

      - name: 发送压缩文件到 Telegram 频道
        run: |
          # 直接使用本地生成的压缩文件路径
          FILE_PATH="$JM_DOWNLOAD_DIR/$ZIP_NAME"
          
          echo "Sending file to Telegram..."
          RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendDocument" \
            -F "chat_id=$TELEGRAM_CHAT_ID" \
            -F "document=@$FILE_PATH" \
            -F "caption=下载的JM本子压缩包")
          
          if [ $? -eq 0 ]; then
            echo "File sent successfully."
          else
            echo "Failed to send file to Telegram."
            exit 1
          fi
